### ISSUE TITLE
Create License

### ISSUE THREAD

**Issue by OscarAblinger** [awesome-global-contributions/action-yq#1]
Which License should we use for this project?
I'm thinking MIT

**Comment by AdrienLemaire** [comment]
Why not keep it CC0? If you can explain the advantages of MIT, I'd love to read about it :)

**Comment by OscarAblinger** [comment]
Well, I originally thought that CC0 was meant only for non-code-content. Turns out, I'm wrong and it is used for OSS, too.

However, if you're interested, I found [this post, comparing using CC0 and GPLv3](https://opensource.stackexchange.com/questions/133/how-could-using-code-released-under-cc0-infringe-on-the-authors-patents) and why using libraries with the former license might be a bit dangerous.

In reality, this isn't a library, so it doesn't really matter, because it's likely not gonna be used anywhere outside of github actions, where it doesn't really matter.
